# Generated by Django 4.2.5 on 2023-09-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='is_leaf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='nextSection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='main.section'),
        ),
        migrations.AddField(
            model_name='card',
            name='article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article'),
        ),
    ]
