# Generated by Django 4.2.5 on 2023-09-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_card_is_leaf_card_nextsection_card_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_list', to='main.section'),
        ),
    ]
