# Generated by Django 4.2.5 on 2023-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='context',
        ),
    ]
