# Generated by Django 4.2.5 on 2023-09-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_card_description_card_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imgage',
            new_name='image',
        ),
    ]
