# Generated by Django 4.1.7 on 2023-10-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_destination', to='main.card'),
        ),
        migrations.AddField(
            model_name='section',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_destination', to='main.card'),
        ),
    ]
